---
- name: Set up CORS Anywhere Server with SSL from Let's Encrypt
  hosts: all
  remote_user: root
  become: yes
  become_user: root
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Node.js, NPM, nginx, and software-properties-common
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - nodejs
        - npm
        - nginx
        - software-properties-common

    - name: Add Certbot repository
      apt:
        name: certbot
        state: present
      become: yes

    - name: Install Certbot
      apt:
        name: certbot
        state: latest
    
    - name: Install Certbot Nginx plugin
      apt:
        name: python3-certbot-nginx
        state: present

    - name: Obtain SSL certificate from Let's Encrypt
      shell: certbot --nginx -d cors.kira.network --non-interactive --agree-tos --email hello@kira.network
      args:
        creates: /etc/letsencrypt/live/cors.kira.network/fullchain.pem
      when: not ansible_check_mode

    - name: Clone CORS Anywhere repository
      git:
        repo: 'https://github.com/Rob--W/cors-anywhere.git'
        dest: /opt/cors-anywhere
        clone: yes
        update: yes

    - name: Install CORS Anywhere dependencies
      npm:
        path: /opt/cors-anywhere

    - name: Create Nginx configuration for CORS Anywhere
      blockinfile:
        path: /etc/nginx/sites-available/cors-anywhere
        create: yes
        block: |
          server {
              listen 443 ssl;
              server_name cors.kira.network www.cors.kira.network.com;  

              ssl_certificate /etc/letsencrypt/live/cors.kira.network/fullchain.pem;  
              ssl_certificate_key /etc/letsencrypt/live/cors.kira.network/privkey.pem;  

              ssl_protocols TLSv1.2 TLSv1.3;  
              ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256...';
              ssl_prefer_server_ciphers on;

              location / {
                  proxy_pass http://localhost:1234;  # Replace with CORS-Anywhere address
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }


    - name: Enable Nginx CORS Anywhere configuration
      ansible.builtin.file:
        src: /etc/nginx/sites-available/cors-anywhere
        dest: /etc/nginx/sites-enabled/cors-anywhere
        state: link

    - name: Remove Nginx default configuration from sites-enabled
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Remove Nginx default configuration from sites-available
      ansible.builtin.file:
        path: /etc/nginx/sites-available/default
        state: absent

    - name: Reload Nginx to apply new configuration
      systemd:
        name: nginx
        state: reloaded

    - name: Start CORS Anywhere server
      shell: 'cd /opt/cors-anywhere && npm start &'
      async: 15
      poll: 0
      when: not ansible_check_mode



